#!/bin/bash

if [ "Linux" != "$(uname -s)" ]; then
    echo "You can only build this on a Linux host."
    exit 2
fi

if [ -n "$(git status --porcelain)" ]; then
    echo
    echo "There are uncommitted modifications - are you absolutely sure you want to make a package???"
    echo
fi

DESCRIBE=$(git describe)
DIST='dist'
TARGET="target/bom-solar-webservice-${DESCRIBE}.tar.gz"

rm -rf dist && mkdir -p dist
stack clean
stack build --copy-bins

mkdir -p target
tar czf ${TARGET} \
  Changelog.md \
  -C ${DIST} \
    bom-solar-webservice \
&& echo "Built package ${TARGET}"
